clear; clc; rng('default'); rng(0); close all; tic;
load('./Data/Data_Fig2a.mat', 'x0', 'x_low', 'x_high');

mkdir('./Figure/'); mkdir('./Data/')

Empirical_fw_low

load('./Data/Data_Empirical_fw.mat', 'Data')
Reff1 = Data(:,:,3);
etaeff1 = Data(:,:,4);
load('./Data/Data_Empirical_fl.mat', 'Data')
Reff2 = Data(:,:,3);
etaeff2 = Data(:,:,4);
load('./Data/Data_Empirical_fn_scale_High.mat', 'Data')
Reff3 = Data(:,:,3);
etaeff3 = Data(:,:,4);
load('./Data/Data_Empirical_fn_scale_Low.mat', 'Data')
Reff4 = Data(:,:,3);
etaeff4 = Data(:,:,4);
load('./Data/Data_Empirical_fw_Low.mat', 'Data')
Reff6 = Data(:,:,3);
etaeff6 = Data(:,:,4);

Fig = figure(Name='R_eff vs eta_eff', ...
    NumberTitle='off');
fplot(x_high, [0,1], ...
    LineStyle='-', ...
    LineWidth=2, ...
    Color=[0.4940 0.1840 0.5560], ...
    DisplayName='Sustainable')
hold on
fplot(x_low, [0,1], ...
    LineStyle='--', ...
    LineWidth=2, ...
    Color=[47 127 193]/255, ...
    DisplayName='Unstable')
hold on
fplot(x0, [0,1], ...
    LineStyle='-', ...
    Color=[73 108 136]/255, ...
    LineWidth=2, ...
    DisplayName='Depleted');
plot(etaeff1, Reff1, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[177 86 70]/255)
hold on
plot(etaeff4, Reff4, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[0.85 0.325 0.098])
hold on
plot(etaeff3, Reff3, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[0.929 0.694 0.125])
hold on
plot(etaeff2, Reff2, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[214 39 40]/255)
hold on
plot(etaeff6, Reff6, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[56 89 137]/255)
ylim([-0.05,1.1])
xlabel('\eta_{eff}')
ylabel('R_{eff}');
set(gca, ...
    FontSize=18, ...
    FontName='Arial');

saveas(Fig, './Figure/Fig6d', 'epsc')
saveas(Fig, './Figure/Fig6d')