clear; clc; rng('default'); rng(0); close all; tic;

mkdir('./Figure/'); mkdir('./Data/')

WS_Pro

load('.\Data\Data_FigS2b.mat', 'connectivity', 'pro', 'critical_pro')

Fig = figure(Name='Probability vs Connectivity', ...
    NumberTitle='off');
h1 = plot(connectivity, pro, ...
    LineStyle='none', ...
    Marker='.', ...
    MarkerSize=20, ...
    DisplayName='Numerical');
hold on
h2 = line([0,critical_pro], [1,1], ...
    LineWidth=2, ...
    Color='#D95319', ...
    DisplayName='Theoretical');
hold on
line([critical_pro,critical_pro], [0,1], ...
    LineWidth=2, ...
    Color='#D95319')
hold on
line([critical_pro,1], [0,0], ...
    LineWidth=2, ...
    Color='#D95319');
legend([h1, h2], Location='southwest')
xlabel('Connectivity')
ylabel('Probability')
xlim([0 1])
ylim([-0.1,1.1])
set(gca, FontSize=18, ...
    FontName='Arial', ...
    XTick=[0.1,0.3,0.5,0.7,0.9]);

saveas(Fig, './Figure/FigS2b', 'epsc')
saveas(Fig, './Figure/FigS2b')