clear; clc; rng('default'); rng(0); close all; tic;

mkdir('./Figure/'); mkdir('./Data/')

ER_fn_High; ER_fn_Low; ER_fn_Random;

load('.\Data\Data_ER_fn_High.mat', 'Data')
Reff1 = Data(:,:,3);
etaeff1 = Data(:,:,4);
R1 = Data(:,:,1);
load('.\Data\Data_ER_fn_Low.mat', 'Data')
Reff2 = Data(:,:,3);
etaeff2 = Data(:,:,4);
R2 = Data(:,:,1);
load('.\Data\Data_ER_fn_Random.mat', 'Data')
Reff3 = Data(:,:,3);
etaeff3 = Data(:,:,4);
R3 = Data(:,:,1);

ReffMean1 = mean(Reff1);
ReffMean2 = mean(Reff2);
ReffMean3 = mean(Reff3);
etaeffMean1 = mean(etaeff1);
etaeffMean2 = mean(etaeff2);
etaeffMean3 = mean(etaeff3);
RMean1 = mean(R1);
RMean2 = mean(R2);
RMean3 = mean(R3);
WightRate = Data(1,:,5);
n = 4;
WightRate = WightRate(1:n:end);
ReffMean1 = ReffMean1(1:n:end);
ReffMean2 = ReffMean2(1:n:end);
ReffMean3 = ReffMean3(1:n:end);
RMean1 = RMean1(1:n:end);
RMean2 = RMean2(1:n:end);
RMean3 = RMean3(1:n:end);
etaeffMean1 = etaeffMean1(1:n:end);
etaeffMean2 = etaeffMean2(1:n:end);
etaeffMean3 = etaeffMean3(1:n:end);

Fig1 = figure(Name='R_{eff} vs f_n', ...
    NumberTitle='off');
plot(WightRate, ReffMean3, ...
    LineStyle='--', ...
    Marker='o', ...
    Color=[0 0.447 0.741], ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (i) for original system')
hold on
plot(WightRate, ReffMean2, ...
    LineStyle='--', ...
    Marker='s', ...
    Color=[0.85 0.325 0.098], ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (ii) for original system')
hold on
plot(WightRate, ReffMean1, ...
    LineStyle='--', ...
    Marker='d', ...
    Color=[0.929 0.694 0.125], ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (iii) for original system')
hold on
plot(WightRate, RMean3, ...
    LineStyle='-', ...
    Marker='p', ...
    Color=[0.494 0.184 0.556], ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (i) for 1-D system')
hold on
plot(WightRate, RMean2, ...
    LineStyle='-', ...
    Marker='h', ...
    Color=[0.466 0.674 0.188], ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (ii) for 1-D system')
hold on
plot(WightRate, RMean1, ...
    LineStyle='-', ...
    Marker='<', ...
    Color=[0.301 0.745 0.933], ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (iii) for 1-D system');
legend(Position=[0.179828571428571,0.682045241501218,0.426799999999999,0.24404761223566], ...
    FontSize=10, ...
    FontName='Arial')
xlabel('f_n')
ylabel('R_{eff}')
set(gca, FontSize=18, ...
    FontName='Arial', ...
    XTick=[0,0.2,0.4,0.6,0.8])

Fig2 = figure(Name='eta_{eff} vs f_n', ...
    NumberTitle='off');
plot(WightRate, etaeffMean3, ...
    LineStyle='-', ...
    Marker='o', ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (i)')
hold on
plot(WightRate, etaeffMean2, ...
    LineStyle='-', ...
    Marker='^', ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (ii)')
hold on
plot(WightRate, etaeffMean1, ...
    LineStyle='-', ...
    Marker='d', ...
    MarkerSize=8, ...
    LineWidth=2, ...
    DisplayName='Strategy (iii)')
legend(Location='Best', ...
    FontSize=16, ...
    FontName='Arial');
xlabel('f_n')
ylabel('\eta_{eff}')
set(gca, FontSize=18, ...
    FontName='Arial', ...
    XTick=[0,0.2,0.4,0.6,0.8])

saveas(Fig1, './Figure/Fig3a', 'epsc')
saveas(Fig1, './Figure/Fig3a');
saveas(Fig2, './Figure/FigS4a', 'epsc')
saveas(Fig2, './Figure/FigS4a');