close all; clear; clc; rng('default'); rng(0); tic;

load('.\Data\Data_bif.mat', 't_lin', 'x_high_lin', 'x_low_lin', 'eta_eff_c')
load('.\Data\Data_Reff_etaeff.mat')

Fig = figure(Name='R_eff vs eta_eff', ...
    NumberTitle='off');

line2 = plot(t_lin(1:end-2), x_high_lin(1:end-2), ...
    LineStyle='-', ...
    Color=[47 127 193]/255, ...
    LineWidth=3, ...
    DisplayName='Sustainable');
hold on
line3 = plot(t_lin(1:end-2), x_low_lin(1:end-2), ...
    LineStyle='--', ...
    Color=[73 108 136]/255, ...
    LineWidth=3, ...
    DisplayName='Unstable');
hold on
for i = a:b
    plot(eta(i), Reff(i), ...
        Marker='.', ...
        Color=color{i}, ...
        MarkerSize=32, ...
        LineStyle='none');
    hold on
end
text(0, 0.95e8, '\times10^7', ...
    FontSize=18, ...
    FontName='Arial')
legend([line2 line3], ...
    Location='northeast', ...
    Box='off')
xlim([0, 100])
ylim([9e5, 7.5e7])
xlabel('\eta_{eff}')
ylabel('R_{eff} (ton)');
set(gca, FontSize=18, ...
    FontName='Arial', ...
    yscale='log', ...
    YTick=[1e6, 3e6, 1e7, 3e7], ...
    YTickLabel={'0.1', '0.3', '1.0', '3.0'})

saveas(Fig, './Figure/Fig7b', 'epsc')
saveas(Fig, './Figure/Fig7b')