clear; clc; rng('default'); rng(0); close all; tic;
load('./Data/Data_Fig2a.mat', 'x_high', 'x_low', 'x_0')

mkdir('./Figure/'); mkdir('./Data/')

InnerMongolia_fn_High; InnerMongolia_fn_Low; InnerMongolia_fn_Random; InnerMongolia_fl; InnerMongolia_fw; InnerMongolia_fw_low

load('./Data/Data_InnerMongolia_fw.mat', 'Data')
Reff1 = Data(:,:,3);
etaeff1 = Data(:,:,4);
load('./Data/Data_InnerMongolia_fl.mat', 'Data')
Reff2 = Data(:,:,3);
etaeff2 = Data(:,:,4);
load('./Data/Data_InnerMongolia_fn_High.mat', 'Data')
Reff3 = Data(:,:,3);
etaeff3 = Data(:,:,4);
load('./Data/Data_InnerMongolia_fn_Low.mat', 'Data')
Reff4 = Data(:,:,3);
etaeff4 = Data(:,:,4);
load('./Data/Data_InnerMongolia_fn_Random.mat', 'Data')
Reff5 = Data(:,:,3);
etaeff5 = Data(:,:,4);
load('./Data/Data_InnerMongolia_fw_low.mat', 'Data')
Reff6 = Data(:,:,3);
etaeff6 = Data(:,:,4);

Fig = figure(Name='R_eff vs eta_eff', ...
    NumberTitle='off');
fplot(x_high, [0,1], ...
    LineStyle='-', ...
    LineWidth=2, ...
    Color=[0.4940 0.1840 0.5560], ...
    DisplayName='Sustainable')
hold on
fplot(x_low, [0,1], ...
    LineStyle='--', ...
    LineWidth=2, ...
    Color=[47 127 193]/255, ...
    DisplayName='Unstable')
hold on
fplot(x_0, [0,1], ...
    LineStyle='-', ...
    LineWidth=2, ...
    Color=[73 108 136]/255, ...
    DisplayName='Depleted')
% legend('Location','northeast');
ylim([-0.05,1.1])
xlabel('\eta_{eff}')
ylabel('R_{eff}')
plot(etaeff1, Reff1, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[177 86 70]/255)
hold on
plot(etaeff4, Reff4, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[0.85 0.325 0.098])
hold on
plot(etaeff3, Reff3, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[0.929 0.694 0.125])
hold on
plot(etaeff2, Reff2, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[214 39 40]/255)
hold on
plot(etaeff6, Reff6, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[56 89 137]/255)
hold on
plot(etaeff5, Reff5, ...
    Marker='.', ...
    LineStyle='none', ...
    MarkerSize=18, ...
    Color=[0.3010 0.7450 0.9330])
set(gca, FontSize=18, ...
    FontName='Arial');

saveas(Fig,'./Figure/FigS8b','epsc')
saveas(Fig,'./Figure/FigS8b')